name: Build and Push Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get latest release version
        id: get_version
        run: |
          VERSION_TAG=$(curl -s https://api.github.com/repos/miurla/morphic/releases/latest | jq -r .tag_name)
          echo "VERSION_TAG=${VERSION_TAG}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Check if image exists
        id: check_image
        run: |
          if docker manifest inspect shenlw/morphic:${{ env.VERSION_TAG }} > /dev/null 2>&1; then
            echo "Image already exists, skipping build"
            echo "IMAGE_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Image does not exist, proceeding with build"
            echo "IMAGE_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: env.IMAGE_EXISTS == 'false'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: env.IMAGE_EXISTS == 'false'

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        if: env.IMAGE_EXISTS == 'false'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            shenlw/morphic:${{ env.VERSION_TAG }}
            shenlw/morphic:latest
          build-args: |
            GIT_TAG=${{ env.VERSION_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
